application: storybookwebapp
version: betabeginsentences
runtime: python
api_version: 1

default_expiration: "1s"

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico
  upload: images/favicon\.ico

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /data
  static_dir: data

- url: /cleanup
  script: cleanup.py
  login: admin

- url: /clean_games
  script: cleanup.py
  login: admin

- url: /.*
  script: storybook.py

