application: storybookwebapp
version: beta
runtime: python
api_version: 1

default_expiration: "1s"

handlers:
- url: /favicon\.ico
  static_files: images/StorybookIcon16.ico
  upload: images/StorybookIcon32\.ico

- url: /storybook_icon\.png
  static_files: images/StorybookIcon75.png
  upload: images/StorybookIcon75\.png

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /data
  static_dir: data

- url: /cleanup
  script: cleanup.py
  login: admin

- url: /clean_games
  script: cleanup.py
  login: admin

- url: /.*
  script: storybook.py

