application: storybookwebapp
version: prerelease
runtime: python
api_version: 1

default_expiration: "5h"

handlers:
- url: /favicon\.ico
  static_files: images/StorybookIcon16.ico
  upload: images/StorybookIcon32\.ico

- url: /font\.ttf
  static_files: fonts/Griffy-Regular.ttf
  upload: fonts/Griffy-Regular\.ttf
  mime_type: application/x-font-ttf

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /data
  static_dir: data

- url: /cleanup
  script: cleanup.py
  login: admin

- url: /clean_games
  script: cleanup.py
  login: admin

- url: /.*
  script: storybook.py

