from google.appengine.ext import db, webapp

class LastUsedGameID(db.Model):
    game_id = db.IntegerProperty()

class Game(db.Model):
    game_id = db.IntegerProperty()
    created = db.DateTimeProperty()
    can_vote = db.BooleanProperty()
    current_players = db.IntegerProperty()
    story = db.ListProperty(str)
    users = db.ListProperty(str)
    next_parts = db.ListProperty(str)
    users_next_parts = db.ListProperty(str)
    started = db.BooleanProperty()
    end_submission_time = db.DateTimeProperty()
    end_display_time = db.DateTimeProperty()
    can_submit = db.BooleanProperty()
    end_vote_time = db.DateTimeProperty()
    end_sentence = db.StringProperty()
    votes = db.ListProperty(int)
    users_voted = db.ListProperty(str)
    display_phase = db.BooleanProperty()
    winning_sentences = db.ListProperty(str)
    winning_users = db.ListProperty(str)
    winning_users_names = db.ListProperty(str)
    num_phases = db.IntegerProperty()
    finished = db.BooleanProperty()
    end_voting = db.BooleanProperty()
    end_users_voted = db.ListProperty(str)
    end_votes = db.ListProperty(int)
    end_end_vote_time = db.DateTimeProperty()
    game_ended = db.DateTimeProperty()
    scores = db.ListProperty(int)
    recent_score_data = db.ListProperty(int)
    went_to_submission = db.BooleanProperty()
    start_sentence = db.StringProperty()
    achievements = db.ListProperty(str)
